namespace:
  name: eiersaft

deployment:
  name: eiersaft
  image: __IMAGE_NAME__:__TAG__
  imagePullPolicy: IfNotPresent
  revisionHistoryLimit: 1
  replicas: 1
  labels:
    app: eiersaftme
  requests:
    cpu: 100m
    memory: 100Mi
  limit:
    cpu: 300m
    memory: 300Mi

ingress:
  name: eiersaft
  hosts:
    - name: eiersaft.me
  secret: tls-eiersaft
  issuer: letsencrypt-issuer

service:
  name: eiersaft
  port: 8080
  targetPort: 8080
  appSelector: eiersaftme